### PR TITLE
Remove $where to comply with Atlas free tier

### PR DESCRIPTION
**Pull request by dukedhx**
- Mapr (or $where clause) is unsupported on MongoDB Atlas free tier and temporarily removed for sake of deployment there
- Allow to specify MongoDB connection string as env var

### CODE REVIEW

**Comment by libvarun** [comment]
I tried deploying, 2 observations:
1) In heroku, rcdb url and port needs to be entered even if connection string is provided, which is fine because app is deployed successfully.
2) Even though app is deployed successfully, i'm getting 503 error
https://varun-rcdb.herokuapp.com/

**Comment by dukedhx** [comment]
If you define dbhost then connection string would be ignored.
What’s your log output and env vars... You usually get 503 on Heroku when the app fails to start

**Comment by libvarun** [comment]
But after clicking on 'deploy on heroku' button dbhost url and port are required, whitout those user won't be able to deploy, but i'm guessing it's fine because there's no mongo error.
should i try null for those two?

log output:
2019-04-05T06:27:47.366671+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2019-04-05T06:27:47.366829+00:00 app[web.1]: npm ERR!     npm bugs forge-rcdb
2019-04-05T06:27:47.366988+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2019-04-05T06:27:47.367140+00:00 app[web.1]: npm ERR!     npm owner ls forge-rcdb
2019-04-05T06:27:47.367291+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2019-04-05T06:27:47.371936+00:00 app[web.1]: 
2019-04-05T06:27:47.371940+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2019-04-05T06:27:47.371978+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2019-04-05T06:27:47.448490+00:00 heroku[web.1]: State changed from starting to crashed
2019-04-05T06:27:47.431518+00:00 heroku[web.1]: Process exited with status 1
2019-04-05T06:37:50.331836+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=varun-rcdb.herokuapp.com request_id=f3f28c4c-3469-4d2f-8108-0329725a20e4 fwd="49.206.8.83" dyno= connect= service= status=503 bytes= protocol=https
2019-04-05T06:37:52.494942+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=varun-rcdb.herokuapp.com request_id=54d42264-b8b4-4081-b2dc-6a07752376f0 fwd="49.206.8.83" dyno= connect= service= status=503 bytes= protocol=https

**Comment by dukedhx** [comment]
My bad fix the required fields.

Paste full build log or add me as a collaborate if the error persists

**Comment by libvarun** [comment]
still same outcome, added you as collaborator.

**Comment by dukedhx** [comment]
dukedhx@hotmail.com

**Comment by libvarun** [comment]
added your hotmail id as collaborator.

**Comment by dukedhx** [comment]
Do not use the srv scheme which is not supported by current version of mongodb version in deps. Use the standard cluster connection. And as said the connection string and dbhost are mutual exclusive - with your env var the connection string won’t get picked up.

**Comment by libvarun** [comment]
Thanks it's working now.

**Comment by libvarun** [comment]
i think callback url error is coming because host url is hard coded in config:
const HOST_URL = 'https://forge-rcdb.autodesk.io'
it should be either taken fron env variable or resolve the host url in node.

**Pull request closed without merging**
