### PR TITLE
 Add Heroku-specific build command and delete yarn.lock

### PR DESCRIPTION
**Pull request by dukedhx**

### CODE REVIEW

**Comment by dukedhx** [comment]
**Enable to specify custom connection string**

- Can now specify custom connection string in full with schema and shards to accommodate cluster connection.
- Update README to address MongoDB Atlas migration
- Tested and passed with MongoDB Atlas:
image

**Comment by augustogoncalves** [comment]
thanks, @dukedhx , have you tested on heroku too? I know that's where the problem appears

**Comment by dukedhx** [comment]
No don’t think I need to because the problem was with the connection string and nothing else and it was NOT specific to Heroku - just like the issue with production building earlier it’d affect your local environment as well. Just because that a particular partner ran into the issue when deploying to Heroku does NOT make this heroku specific.

Please try to understand the problem was that there was no way to specify the connection string directly so one can accommodate for different connection schemas for standalone and clustered instances. We can set up a call to discuss you’d like to learn more.

Above all I am not sure why it took so long to merge this PR - with the presence of yarn lock one won’t even be able to deploy to Heroku right out of the box.

**Comment by dukedhx** [comment]
Tested the latest commit on Heroku (https://sb233.herokuapp.com) with the config below:
```
database: {
    type: 'mongo',
    connectionString: 'mongodb://sb233:<password>@cluster0-shard-00-00-u9dtd.mongodb.net:27017,cluster0-shard-00-01-u9dtd.mongodb.net:27017,cluster0-shard-00-02-u9dtd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true',
    dbhost: '',
    dbName: "sb233",
    user: '',
    pass: '',
    port: '',
...
```
Didn't import the models though:
image

**Comment by augustogoncalves** [comment]
thanks @dukedhx , so the deployment works
as (I believe) your database is empty, then it doesn't show models... does it show any error on the logs? if not, then it's working :)

**Comment by dukedhx** [comment]
No models imported as was said in my previous comment because the point was to test the connection and no errors in the logs either Silva is already using this for prod so if he doesn’t find anything out of order then we are good - I had to explain to him what you and Varun told him about these platforms not working with each other was incorrect so pls do your due research next time.

**Pull request merged**
